<a href="https://colab.research.google.com/github/Nikulkumar-Dabhi/Data_Science/blob/main/Data_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data transformation is the process of converting data from one format or structure into another. This is often necessary to prepare data for analysis or to make it compatible with different systems. Python offers several built-in functions to help with these tasks.

1. map()
The map() function applies a given function to each item of an iterable (e.g., a list, tuple) and returns an iterator with the results.
It's useful for transforming each element of a dataset individually.

In [ ]:
numbers = [1, 2, 3, 4, 5]
squares = list(map(lambda x: x**2, numbers))
print(squares)

[1, 4, 9, 16, 25]


2. filter()
The filter() function constructs an iterator from elements of an iterable for which a function returns

In [ ]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Function to check if a number is even
def is_even(number):
  return number % 2 == 0

# Use filter to get even numbers
even_numbers = list(filter(is_even, numbers))

print(even_numbers)


[2, 4, 6, 8, 10]


sorted()

The sorted() function returns a new sorted list from the items in an iterable.

Use key=str.lower or a custom function to sort case-insensitively.

In [ ]:
data = [5, 2, 8, 1, 9]
sorted_data = sorted(data,reverse=False)
print(sorted_data)

data = ['apple', 'banana', 'Orange']
sorted_data_case_insensitive = sorted(data, key=str.lower)
print(sorted_data_case_insensitive)

[1, 2, 5, 8, 9]
['apple', 'banana', 'Orange']


In [ ]:
data = ['Zebra', 'apple', 'Banana', '42', '!', 'cat', 'Dog', '#']

sorted_data = sorted(data)
print(sorted_data)

#Sequence
# 1. Symbol
# 2. numbers
# 3. Uppercase
# 4. Lowercase


['!', '#', '42', 'Banana', 'Dog', 'Zebra', 'apple', 'cat']


data = ['Zebra', 'apple', 'Banana', '42', '!', 'cat', 'Dog', '#']

sorted_data = sorted(data)
print(sorted_data)


reduce()

Zip

Matrix Transformations

In data science and machine learning, matrices are often used to represent datasets, where rows represent data points and columns represent features or variables. Matrix transformations involve applying mathematical operations to a matrix to change its values or structure. These transformations are fundamental to various data analysis and modeling tasks.

Reshaping

In [ ]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6]])
reshaped_matrix = matrix.reshape((3, 2))  # Reshape to 3 rows, 2 columns
reshaped_matrix,matrix


(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

Transposing

Transposing flips a matrix over its diagonal, swapping rows and columns.
You can use the .T attribute or np.transpose() in NumPy.



In [ ]:
import numpy as np
matrix = np.array([[1, 2], [3, 4]])
transposed_matrix = matrix.T
transposed_matrix

array([[1, 3],
       [2, 4]])

In [ ]:
matrix = np.array([[1, 2], [3, 4]])
transposed_matrix = np.transpose(matrix)
transposed_matrix

array([[1, 3],
       [2, 4]])

### Scaling
Scaling involves multiplying all elements of a matrix by a constant factor.
You can simply use the multiplication operator (*) in NumPy.

In [ ]:
j=9

In [ ]:
import numpy as np
matrix = np.array([[1, 2], [3, 4]])
scaled_matrix = matrix * 2  , matrix * 0.5,matrix * j
scaled_matrix

(array([[2, 4],
        [6, 8]]),
 array([[0.5, 1. ],
        [1.5, 2. ]]),
 array([[ 9, 18],
        [27, 36]]))

Element-wise Operations

In [ ]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
sum_matrix = matrix1 + matrix2
sum_matrix

array([[ 6,  8],
       [10, 12]])

Matrix Multiplication

In [ ]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
product_matrix = np.dot(matrix1, matrix2)
product_matrix

array([[19, 22],
       [43, 50]])

Determinant
The determinant of a square matrix is a scalar value that provides information about its properties, such as invertibility.

In [3]:
 import numpy as np
matrix = np.array([[1, 2], [3, 4]])
determinant = np.linalg.det(matrix)

determinant

np.float64(-2.0000000000000004)